//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public int EntryID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    
        public virtual User User { get; set; }
    }
}
